name: CICD

# 이벤트가 실행될 workflow 정의
on:
  push:
    branches:
      - main

# 작업 정의(jobs): build, deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Create env file
        run: |
          touch .env
          echo "${{Secret.VITE_AUTH_CLIENT_ID}}" > .env
      - name: Sign in to Docker Hub
        run: docker login -u ${{DOCKER_USERNAME}} -p ${{DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t hangeol1829/aicc6_task_front
      - name: Push Docker Image
        run: docker push hangeol1829/aicc6_task_front

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker Hub
        run: docker pull hangeol1829/aicc6_task_front
      - name: Delete Existing container
        run: docker rm -f task-container
      - name: Run Container
        run: docker run -d -p 80:80 --name task-container hangeol1829/aicc6_task_front
